/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.AlertListCode;
import io.swagger.client.model.AlertListDriver;
import io.swagger.client.model.AlertListLevel;
import io.swagger.client.model.AlertListVehicle;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * AlertListList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T13:49:13.196Z[GMT]")
public class AlertListList {
  @SerializedName("fuel_level")
  private BigDecimal fuelLevel = null;

  @SerializedName("fuel_level_on_raise_start")
  private BigDecimal fuelLevelOnRaiseStart = null;

  @SerializedName("action_status")
  private Integer actionStatus = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("nav_system_object_uid")
  private String navSystemObjectUid = null;

  @SerializedName("created_at")
  private Integer createdAt = null;

  @SerializedName("is_closed")
  private Boolean isClosed = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("vehicle")
  private AlertListVehicle vehicle = null;

  @SerializedName("code")
  private AlertListCode code = null;

  @SerializedName("driver")
  private AlertListDriver driver = null;

  @SerializedName("level")
  private AlertListLevel level = null;

  @SerializedName("status")
  private Integer status = null;

  @SerializedName("is_maintenance_enabled")
  private Boolean isMaintenanceEnabled = null;

  public AlertListList fuelLevel(BigDecimal fuelLevel) {
    this.fuelLevel = fuelLevel;
    return this;
  }

   /**
   * Get fuelLevel
   * @return fuelLevel
  **/
  @Schema(example = "643.21", description = "")
  public BigDecimal getFuelLevel() {
    return fuelLevel;
  }

  public void setFuelLevel(BigDecimal fuelLevel) {
    this.fuelLevel = fuelLevel;
  }

  public AlertListList fuelLevelOnRaiseStart(BigDecimal fuelLevelOnRaiseStart) {
    this.fuelLevelOnRaiseStart = fuelLevelOnRaiseStart;
    return this;
  }

   /**
   * Get fuelLevelOnRaiseStart
   * @return fuelLevelOnRaiseStart
  **/
  @Schema(example = "445.14", description = "")
  public BigDecimal getFuelLevelOnRaiseStart() {
    return fuelLevelOnRaiseStart;
  }

  public void setFuelLevelOnRaiseStart(BigDecimal fuelLevelOnRaiseStart) {
    this.fuelLevelOnRaiseStart = fuelLevelOnRaiseStart;
  }

  public AlertListList actionStatus(Integer actionStatus) {
    this.actionStatus = actionStatus;
    return this;
  }

   /**
   * Get actionStatus
   * @return actionStatus
  **/
  @Schema(example = "2", description = "")
  public Integer getActionStatus() {
    return actionStatus;
  }

  public void setActionStatus(Integer actionStatus) {
    this.actionStatus = actionStatus;
  }

  public AlertListList id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "59", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public AlertListList navSystemObjectUid(String navSystemObjectUid) {
    this.navSystemObjectUid = navSystemObjectUid;
    return this;
  }

   /**
   * Get navSystemObjectUid
   * @return navSystemObjectUid
  **/
  @Schema(example = "5e131cde0e4eb7.07110534", description = "")
  public String getNavSystemObjectUid() {
    return navSystemObjectUid;
  }

  public void setNavSystemObjectUid(String navSystemObjectUid) {
    this.navSystemObjectUid = navSystemObjectUid;
  }

  public AlertListList createdAt(Integer createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @Schema(example = "1539334920", description = "")
  public Integer getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(Integer createdAt) {
    this.createdAt = createdAt;
  }

  public AlertListList isClosed(Boolean isClosed) {
    this.isClosed = isClosed;
    return this;
  }

   /**
   * Get isClosed
   * @return isClosed
  **/
  @Schema(example = "false", description = "")
  public Boolean isIsClosed() {
    return isClosed;
  }

  public void setIsClosed(Boolean isClosed) {
    this.isClosed = isClosed;
  }

  public AlertListList description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @Schema(example = "Some Desc", description = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AlertListList vehicle(AlertListVehicle vehicle) {
    this.vehicle = vehicle;
    return this;
  }

   /**
   * Get vehicle
   * @return vehicle
  **/
  @Schema(description = "")
  public AlertListVehicle getVehicle() {
    return vehicle;
  }

  public void setVehicle(AlertListVehicle vehicle) {
    this.vehicle = vehicle;
  }

  public AlertListList code(AlertListCode code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code
  **/
  @Schema(description = "")
  public AlertListCode getCode() {
    return code;
  }

  public void setCode(AlertListCode code) {
    this.code = code;
  }

  public AlertListList driver(AlertListDriver driver) {
    this.driver = driver;
    return this;
  }

   /**
   * Get driver
   * @return driver
  **/
  @Schema(description = "")
  public AlertListDriver getDriver() {
    return driver;
  }

  public void setDriver(AlertListDriver driver) {
    this.driver = driver;
  }

  public AlertListList level(AlertListLevel level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @Schema(description = "")
  public AlertListLevel getLevel() {
    return level;
  }

  public void setLevel(AlertListLevel level) {
    this.level = level;
  }

  public AlertListList status(Integer status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(example = "1", description = "")
  public Integer getStatus() {
    return status;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public AlertListList isMaintenanceEnabled(Boolean isMaintenanceEnabled) {
    this.isMaintenanceEnabled = isMaintenanceEnabled;
    return this;
  }

   /**
   * Get isMaintenanceEnabled
   * @return isMaintenanceEnabled
  **/
  @Schema(example = "true", description = "")
  public Boolean isIsMaintenanceEnabled() {
    return isMaintenanceEnabled;
  }

  public void setIsMaintenanceEnabled(Boolean isMaintenanceEnabled) {
    this.isMaintenanceEnabled = isMaintenanceEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlertListList alertListList = (AlertListList) o;
    return Objects.equals(this.fuelLevel, alertListList.fuelLevel) &&
        Objects.equals(this.fuelLevelOnRaiseStart, alertListList.fuelLevelOnRaiseStart) &&
        Objects.equals(this.actionStatus, alertListList.actionStatus) &&
        Objects.equals(this.id, alertListList.id) &&
        Objects.equals(this.navSystemObjectUid, alertListList.navSystemObjectUid) &&
        Objects.equals(this.createdAt, alertListList.createdAt) &&
        Objects.equals(this.isClosed, alertListList.isClosed) &&
        Objects.equals(this.description, alertListList.description) &&
        Objects.equals(this.vehicle, alertListList.vehicle) &&
        Objects.equals(this.code, alertListList.code) &&
        Objects.equals(this.driver, alertListList.driver) &&
        Objects.equals(this.level, alertListList.level) &&
        Objects.equals(this.status, alertListList.status) &&
        Objects.equals(this.isMaintenanceEnabled, alertListList.isMaintenanceEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fuelLevel, fuelLevelOnRaiseStart, actionStatus, id, navSystemObjectUid, createdAt, isClosed, description, vehicle, code, driver, level, status, isMaintenanceEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertListList {\n");
    
    sb.append("    fuelLevel: ").append(toIndentedString(fuelLevel)).append("\n");
    sb.append("    fuelLevelOnRaiseStart: ").append(toIndentedString(fuelLevelOnRaiseStart)).append("\n");
    sb.append("    actionStatus: ").append(toIndentedString(actionStatus)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    navSystemObjectUid: ").append(toIndentedString(navSystemObjectUid)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    isClosed: ").append(toIndentedString(isClosed)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    vehicle: ").append(toIndentedString(vehicle)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    driver: ").append(toIndentedString(driver)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    isMaintenanceEnabled: ").append(toIndentedString(isMaintenanceEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
