/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * AuthorizedUser
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-22T09:48:50.100Z[GMT]")
public class AuthorizedUser {
  @SerializedName("token")
  private String token = null;

  @SerializedName("refresh_token")
  private String refreshToken = null;

  public AuthorizedUser token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @Schema(example = "eyJhbGciOiJSUzI1NiJ9.eyJyb2xlcyI6WyJST0xFX1NVUEVSX0FETUlOIiwiUk9MRV9BTExPV0VEX1RPX1NXSVRDSCIsIlJPTEVfTUFTVEVSIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiYWRtaW5AZ2tlZXAubG9jIiwiaWF0IjoxNTc4NTYxMTgxLCJleHAiOjE1Nzg2NDc1ODF9.OiupFxa4x5YQIwJpXGfQ1Mwmj3OFyPI_MvHBgi7Vtaevcgt0cEA1yh9-g-UJ2E_138E4M5sML5ic1-ZLHMwYzLq7sbUC2TTEZAIOboUczq1I2-ZscSykDdXBErHrvBd9I-9yVNqdeFekaTKwHny3FpQkGYTv5fiwwq9U1eNu-blOyNrvnHvXySWucPyFuSjMqemlnjqUhMj9PV0O8jIFyIadvpKh9KENxLzmnyhsP8JI_p49hRzc2kft5ef3vLJ64Z0Tht25HKloZaagGpCv77op5y1zMohHkx13pzTkLFT8B9tlHzDusajmG2uGnxHBMM3JQl9EBVXhILCMYAjgwsBk0LO5jZWtgxCw1IMfCVwbwd6yt-n3tl6c2Dv3e2Gbh0b7qlTgUOUe9BkAT19D8U4Zr9Db4WVHbr2EKimVuaSPgABvjNx5OtYt-4LHGZm8Vay4qVgrpi7_S9grStwu7t-kGb5Ovssyl0XJu_89o898SFXEl8gkPyvXKR8xk5AEVoyYIDOSa-jWnOpn0J85VT4gIQmZxARXkztaB3LwSSEsK11HrTtDsd0RxcJD-X2fPBdxbhI-i3ZeScf_RgH2Euekf4Ui-BckL4eJbjsMRVY4pLuri9XVl8m2XA72bUDeo1-Ysp7jNSE7HLPHAb6bSMnPDE-BrNZijZ57WixmU9I", description = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public AuthorizedUser refreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

   /**
   * Get refreshToken
   * @return refreshToken
  **/
  @Schema(example = "fec70043a41388a623a0a24802f6aa9ddade14fd54e3785a1549551a8640accf0bea0434e18ea857e49cf3b6f96e1459f85314ac9d2de0ed73340ac125e5f548", description = "")
  public String getRefreshToken() {
    return refreshToken;
  }

  public void setRefreshToken(String refreshToken) {
    this.refreshToken = refreshToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizedUser authorizedUser = (AuthorizedUser) o;
    return Objects.equals(this.token, authorizedUser.token) &&
        Objects.equals(this.refreshToken, authorizedUser.refreshToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(token, refreshToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizedUser {\n");
    
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
