/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CreateProfileUserNavSystemAccessData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T07:00:05.887Z[GMT]")
public class CreateProfileUserNavSystemAccessData {
  @SerializedName("account")
  private String account = null;

  @SerializedName("password")
  private String password = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("apikey")
  private String apikey = null;

  public CreateProfileUserNavSystemAccessData account(String account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account
  **/
  @Schema(example = "keep58", description = "")
  public String getAccount() {
    return account;
  }

  public void setAccount(String account) {
    this.account = account;
  }

  public CreateProfileUserNavSystemAccessData password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @Schema(example = "eTjeqVqjG2uqRM1", description = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public CreateProfileUserNavSystemAccessData username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @Schema(example = "vinz", description = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public CreateProfileUserNavSystemAccessData apikey(String apikey) {
    this.apikey = apikey;
    return this;
  }

   /**
   * Get apikey
   * @return apikey
  **/
  @Schema(example = "24f39dad-716b-4771-9a70-c1ab6fec3fc8", description = "")
  public String getApikey() {
    return apikey;
  }

  public void setApikey(String apikey) {
    this.apikey = apikey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateProfileUserNavSystemAccessData createProfileUserNavSystemAccessData = (CreateProfileUserNavSystemAccessData) o;
    return Objects.equals(this.account, createProfileUserNavSystemAccessData.account) &&
        Objects.equals(this.password, createProfileUserNavSystemAccessData.password) &&
        Objects.equals(this.username, createProfileUserNavSystemAccessData.username) &&
        Objects.equals(this.apikey, createProfileUserNavSystemAccessData.apikey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, password, username, apikey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateProfileUserNavSystemAccessData {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    apikey: ").append(toIndentedString(apikey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
