/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * FrameHistoryList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T13:49:13.196Z[GMT]")
public class FrameHistoryList {
  @SerializedName("latitude")
  private BigDecimal latitude = null;

  @SerializedName("longitude")
  private BigDecimal longitude = null;

  @SerializedName("battery_level")
  private Integer batteryLevel = null;

  @SerializedName("engine_started")
  private Boolean engineStarted = null;

  @SerializedName("is_moving")
  private Boolean isMoving = null;

  @SerializedName("fuel_level")
  private BigDecimal fuelLevel = null;

  @SerializedName("msg_time")
  private Integer msgTime = null;

  public FrameHistoryList latitude(BigDecimal latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @Schema(example = "56.8715508", description = "")
  public BigDecimal getLatitude() {
    return latitude;
  }

  public void setLatitude(BigDecimal latitude) {
    this.latitude = latitude;
  }

  public FrameHistoryList longitude(BigDecimal longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @Schema(example = "53.942966", description = "")
  public BigDecimal getLongitude() {
    return longitude;
  }

  public void setLongitude(BigDecimal longitude) {
    this.longitude = longitude;
  }

  public FrameHistoryList batteryLevel(Integer batteryLevel) {
    this.batteryLevel = batteryLevel;
    return this;
  }

   /**
   * Get batteryLevel
   * @return batteryLevel
  **/
  @Schema(example = "0", description = "")
  public Integer getBatteryLevel() {
    return batteryLevel;
  }

  public void setBatteryLevel(Integer batteryLevel) {
    this.batteryLevel = batteryLevel;
  }

  public FrameHistoryList engineStarted(Boolean engineStarted) {
    this.engineStarted = engineStarted;
    return this;
  }

   /**
   * Get engineStarted
   * @return engineStarted
  **/
  @Schema(description = "")
  public Boolean isEngineStarted() {
    return engineStarted;
  }

  public void setEngineStarted(Boolean engineStarted) {
    this.engineStarted = engineStarted;
  }

  public FrameHistoryList isMoving(Boolean isMoving) {
    this.isMoving = isMoving;
    return this;
  }

   /**
   * Get isMoving
   * @return isMoving
  **/
  @Schema(description = "")
  public Boolean isIsMoving() {
    return isMoving;
  }

  public void setIsMoving(Boolean isMoving) {
    this.isMoving = isMoving;
  }

  public FrameHistoryList fuelLevel(BigDecimal fuelLevel) {
    this.fuelLevel = fuelLevel;
    return this;
  }

   /**
   * Get fuelLevel
   * @return fuelLevel
  **/
  @Schema(example = "13.34", description = "")
  public BigDecimal getFuelLevel() {
    return fuelLevel;
  }

  public void setFuelLevel(BigDecimal fuelLevel) {
    this.fuelLevel = fuelLevel;
  }

  public FrameHistoryList msgTime(Integer msgTime) {
    this.msgTime = msgTime;
    return this;
  }

   /**
   * Get msgTime
   * @return msgTime
  **/
  @Schema(example = "1580997276", description = "")
  public Integer getMsgTime() {
    return msgTime;
  }

  public void setMsgTime(Integer msgTime) {
    this.msgTime = msgTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrameHistoryList frameHistoryList = (FrameHistoryList) o;
    return Objects.equals(this.latitude, frameHistoryList.latitude) &&
        Objects.equals(this.longitude, frameHistoryList.longitude) &&
        Objects.equals(this.batteryLevel, frameHistoryList.batteryLevel) &&
        Objects.equals(this.engineStarted, frameHistoryList.engineStarted) &&
        Objects.equals(this.isMoving, frameHistoryList.isMoving) &&
        Objects.equals(this.fuelLevel, frameHistoryList.fuelLevel) &&
        Objects.equals(this.msgTime, frameHistoryList.msgTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latitude, longitude, batteryLevel, engineStarted, isMoving, fuelLevel, msgTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrameHistoryList {\n");
    
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    batteryLevel: ").append(toIndentedString(batteryLevel)).append("\n");
    sb.append("    engineStarted: ").append(toIndentedString(engineStarted)).append("\n");
    sb.append("    isMoving: ").append(toIndentedString(isMoving)).append("\n");
    sb.append("    fuelLevel: ").append(toIndentedString(fuelLevel)).append("\n");
    sb.append("    msgTime: ").append(toIndentedString(msgTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
