/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * LastAlertListInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-01-22T09:48:50.100Z[GMT]")
public class LastAlertListInner {
  @SerializedName("id")
  private String id = null;

  @SerializedName("frame_id")
  private String frameId = null;

  @SerializedName("version")
  private String version = null;

  @SerializedName("sensor")
  private Object sensor = null;

  @SerializedName("imei")
  private String imei = null;

  @SerializedName("import_status")
  private Integer importStatus = null;

  @SerializedName("msg_time")
  private Integer msgTime = null;

  @SerializedName("latitude")
  private Integer latitude = null;

  @SerializedName("longitude")
  private Integer longitude = null;

  @SerializedName("co2")
  private Integer co2 = null;

  @SerializedName("fuel_consumption")
  private Integer fuelConsumption = null;

  @SerializedName("fuel_levels")
  private List<BigDecimal> fuelLevels = null;

  @SerializedName("aligned_fuel_levels")
  private String alignedFuelLevels = null;

  @SerializedName("fuel_level")
  private BigDecimal fuelLevel = null;

  @SerializedName("vehicle_id")
  private Integer vehicleId = null;

  @SerializedName("vehicle")
  private Object vehicle = null;

  @SerializedName("driver_id")
  private Integer driverId = null;

  @SerializedName("is_day_off")
  private Boolean isDayOff = null;

  @SerializedName("is_maintenance_enabled")
  private Boolean isMaintenanceEnabled = null;

  public LastAlertListInner id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "5e1dcc8f9aedde1a196c2ea4", description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LastAlertListInner frameId(String frameId) {
    this.frameId = frameId;
    return this;
  }

   /**
   * Get frameId
   * @return frameId
  **/
  @Schema(example = "c8d7ab4e-30d7-11e8-9d16-5e1dcc8fc5041-5e1dcc8fc5043", description = "")
  public String getFrameId() {
    return frameId;
  }

  public void setFrameId(String frameId) {
    this.frameId = frameId;
  }

  public LastAlertListInner version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @Schema(example = "c8d7ab4e-30d7-11e8-9d16-5e1dcc8fc5041-5e1dcc8fc5043", description = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public LastAlertListInner sensor(Object sensor) {
    this.sensor = sensor;
    return this;
  }

   /**
   * Get sensor
   * @return sensor
  **/
  @Schema(description = "")
  public Object getSensor() {
    return sensor;
  }

  public void setSensor(Object sensor) {
    this.sensor = sensor;
  }

  public LastAlertListInner imei(String imei) {
    this.imei = imei;
    return this;
  }

   /**
   * Get imei
   * @return imei
  **/
  @Schema(example = "5e1dcbf75c9758.75754550", description = "")
  public String getImei() {
    return imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public LastAlertListInner importStatus(Integer importStatus) {
    this.importStatus = importStatus;
    return this;
  }

   /**
   * Get importStatus
   * @return importStatus
  **/
  @Schema(example = "2", description = "")
  public Integer getImportStatus() {
    return importStatus;
  }

  public void setImportStatus(Integer importStatus) {
    this.importStatus = importStatus;
  }

  public LastAlertListInner msgTime(Integer msgTime) {
    this.msgTime = msgTime;
    return this;
  }

   /**
   * Get msgTime
   * @return msgTime
  **/
  @Schema(example = "1579011215", description = "")
  public Integer getMsgTime() {
    return msgTime;
  }

  public void setMsgTime(Integer msgTime) {
    this.msgTime = msgTime;
  }

  public LastAlertListInner latitude(Integer latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Get latitude
   * @return latitude
  **/
  @Schema(example = "3", description = "")
  public Integer getLatitude() {
    return latitude;
  }

  public void setLatitude(Integer latitude) {
    this.latitude = latitude;
  }

  public LastAlertListInner longitude(Integer longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Get longitude
   * @return longitude
  **/
  @Schema(example = "43", description = "")
  public Integer getLongitude() {
    return longitude;
  }

  public void setLongitude(Integer longitude) {
    this.longitude = longitude;
  }

  public LastAlertListInner co2(Integer co2) {
    this.co2 = co2;
    return this;
  }

   /**
   * Get co2
   * @return co2
  **/
  @Schema(example = "0", description = "")
  public Integer getCo2() {
    return co2;
  }

  public void setCo2(Integer co2) {
    this.co2 = co2;
  }

  public LastAlertListInner fuelConsumption(Integer fuelConsumption) {
    this.fuelConsumption = fuelConsumption;
    return this;
  }

   /**
   * Get fuelConsumption
   * @return fuelConsumption
  **/
  @Schema(example = "0", description = "")
  public Integer getFuelConsumption() {
    return fuelConsumption;
  }

  public void setFuelConsumption(Integer fuelConsumption) {
    this.fuelConsumption = fuelConsumption;
  }

  public LastAlertListInner fuelLevels(List<BigDecimal> fuelLevels) {
    this.fuelLevels = fuelLevels;
    return this;
  }

  public LastAlertListInner addFuelLevelsItem(BigDecimal fuelLevelsItem) {
    if (this.fuelLevels == null) {
      this.fuelLevels = new ArrayList<BigDecimal>();
    }
    this.fuelLevels.add(fuelLevelsItem);
    return this;
  }

   /**
   * Get fuelLevels
   * @return fuelLevels
  **/
  @Schema(description = "")
  public List<BigDecimal> getFuelLevels() {
    return fuelLevels;
  }

  public void setFuelLevels(List<BigDecimal> fuelLevels) {
    this.fuelLevels = fuelLevels;
  }

  public LastAlertListInner alignedFuelLevels(String alignedFuelLevels) {
    this.alignedFuelLevels = alignedFuelLevels;
    return this;
  }

   /**
   * Get alignedFuelLevels
   * @return alignedFuelLevels
  **/
  @Schema(description = "")
  public String getAlignedFuelLevels() {
    return alignedFuelLevels;
  }

  public void setAlignedFuelLevels(String alignedFuelLevels) {
    this.alignedFuelLevels = alignedFuelLevels;
  }

  public LastAlertListInner fuelLevel(BigDecimal fuelLevel) {
    this.fuelLevel = fuelLevel;
    return this;
  }

   /**
   * Get fuelLevel
   * @return fuelLevel
  **/
  @Schema(example = "29.17", description = "")
  public BigDecimal getFuelLevel() {
    return fuelLevel;
  }

  public void setFuelLevel(BigDecimal fuelLevel) {
    this.fuelLevel = fuelLevel;
  }

  public LastAlertListInner vehicleId(Integer vehicleId) {
    this.vehicleId = vehicleId;
    return this;
  }

   /**
   * Get vehicleId
   * @return vehicleId
  **/
  @Schema(example = "1", description = "")
  public Integer getVehicleId() {
    return vehicleId;
  }

  public void setVehicleId(Integer vehicleId) {
    this.vehicleId = vehicleId;
  }

  public LastAlertListInner vehicle(Object vehicle) {
    this.vehicle = vehicle;
    return this;
  }

   /**
   * Get vehicle
   * @return vehicle
  **/
  @Schema(description = "")
  public Object getVehicle() {
    return vehicle;
  }

  public void setVehicle(Object vehicle) {
    this.vehicle = vehicle;
  }

  public LastAlertListInner driverId(Integer driverId) {
    this.driverId = driverId;
    return this;
  }

   /**
   * Get driverId
   * @return driverId
  **/
  @Schema(example = "31", description = "")
  public Integer getDriverId() {
    return driverId;
  }

  public void setDriverId(Integer driverId) {
    this.driverId = driverId;
  }

  public LastAlertListInner isDayOff(Boolean isDayOff) {
    this.isDayOff = isDayOff;
    return this;
  }

   /**
   * Get isDayOff
   * @return isDayOff
  **/
  @Schema(description = "")
  public Boolean isIsDayOff() {
    return isDayOff;
  }

  public void setIsDayOff(Boolean isDayOff) {
    this.isDayOff = isDayOff;
  }

  public LastAlertListInner isMaintenanceEnabled(Boolean isMaintenanceEnabled) {
    this.isMaintenanceEnabled = isMaintenanceEnabled;
    return this;
  }

   /**
   * Get isMaintenanceEnabled
   * @return isMaintenanceEnabled
  **/
  @Schema(description = "")
  public Boolean isIsMaintenanceEnabled() {
    return isMaintenanceEnabled;
  }

  public void setIsMaintenanceEnabled(Boolean isMaintenanceEnabled) {
    this.isMaintenanceEnabled = isMaintenanceEnabled;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LastAlertListInner lastAlertListInner = (LastAlertListInner) o;
    return Objects.equals(this.id, lastAlertListInner.id) &&
        Objects.equals(this.frameId, lastAlertListInner.frameId) &&
        Objects.equals(this.version, lastAlertListInner.version) &&
        Objects.equals(this.sensor, lastAlertListInner.sensor) &&
        Objects.equals(this.imei, lastAlertListInner.imei) &&
        Objects.equals(this.importStatus, lastAlertListInner.importStatus) &&
        Objects.equals(this.msgTime, lastAlertListInner.msgTime) &&
        Objects.equals(this.latitude, lastAlertListInner.latitude) &&
        Objects.equals(this.longitude, lastAlertListInner.longitude) &&
        Objects.equals(this.co2, lastAlertListInner.co2) &&
        Objects.equals(this.fuelConsumption, lastAlertListInner.fuelConsumption) &&
        Objects.equals(this.fuelLevels, lastAlertListInner.fuelLevels) &&
        Objects.equals(this.alignedFuelLevels, lastAlertListInner.alignedFuelLevels) &&
        Objects.equals(this.fuelLevel, lastAlertListInner.fuelLevel) &&
        Objects.equals(this.vehicleId, lastAlertListInner.vehicleId) &&
        Objects.equals(this.vehicle, lastAlertListInner.vehicle) &&
        Objects.equals(this.driverId, lastAlertListInner.driverId) &&
        Objects.equals(this.isDayOff, lastAlertListInner.isDayOff) &&
        Objects.equals(this.isMaintenanceEnabled, lastAlertListInner.isMaintenanceEnabled);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, frameId, version, sensor, imei, importStatus, msgTime, latitude, longitude, co2, fuelConsumption, fuelLevels, alignedFuelLevels, fuelLevel, vehicleId, vehicle, driverId, isDayOff, isMaintenanceEnabled);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LastAlertListInner {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    frameId: ").append(toIndentedString(frameId)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    sensor: ").append(toIndentedString(sensor)).append("\n");
    sb.append("    imei: ").append(toIndentedString(imei)).append("\n");
    sb.append("    importStatus: ").append(toIndentedString(importStatus)).append("\n");
    sb.append("    msgTime: ").append(toIndentedString(msgTime)).append("\n");
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("    co2: ").append(toIndentedString(co2)).append("\n");
    sb.append("    fuelConsumption: ").append(toIndentedString(fuelConsumption)).append("\n");
    sb.append("    fuelLevels: ").append(toIndentedString(fuelLevels)).append("\n");
    sb.append("    alignedFuelLevels: ").append(toIndentedString(alignedFuelLevels)).append("\n");
    sb.append("    fuelLevel: ").append(toIndentedString(fuelLevel)).append("\n");
    sb.append("    vehicleId: ").append(toIndentedString(vehicleId)).append("\n");
    sb.append("    vehicle: ").append(toIndentedString(vehicle)).append("\n");
    sb.append("    driverId: ").append(toIndentedString(driverId)).append("\n");
    sb.append("    isDayOff: ").append(toIndentedString(isDayOff)).append("\n");
    sb.append("    isMaintenanceEnabled: ").append(toIndentedString(isMaintenanceEnabled)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
