/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * TankTypeListInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T07:00:05.887Z[GMT]")
public class TankTypeListInner {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("manufacturer_reference")
  private String manufacturerReference = null;

  @SerializedName("gkeep_id")
  private String gkeepId = null;

  public TankTypeListInner id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public TankTypeListInner manufacturerReference(String manufacturerReference) {
    this.manufacturerReference = manufacturerReference;
    return this;
  }

   /**
   * Get manufacturerReference
   * @return manufacturerReference
  **/
  @Schema(example = "manufacturerReference 1", description = "")
  public String getManufacturerReference() {
    return manufacturerReference;
  }

  public void setManufacturerReference(String manufacturerReference) {
    this.manufacturerReference = manufacturerReference;
  }

  public TankTypeListInner gkeepId(String gkeepId) {
    this.gkeepId = gkeepId;
    return this;
  }

   /**
   * Get gkeepId
   * @return gkeepId
  **/
  @Schema(example = "RV-001", description = "")
  public String getGkeepId() {
    return gkeepId;
  }

  public void setGkeepId(String gkeepId) {
    this.gkeepId = gkeepId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TankTypeListInner tankTypeListInner = (TankTypeListInner) o;
    return Objects.equals(this.id, tankTypeListInner.id) &&
        Objects.equals(this.manufacturerReference, tankTypeListInner.manufacturerReference) &&
        Objects.equals(this.gkeepId, tankTypeListInner.gkeepId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, manufacturerReference, gkeepId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TankTypeListInner {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    manufacturerReference: ").append(toIndentedString(manufacturerReference)).append("\n");
    sb.append("    gkeepId: ").append(toIndentedString(gkeepId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
