/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * UpdateVehicleCategoryVehicleCategoryForm
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T13:49:13.196Z[GMT]")
public class UpdateVehicleCategoryVehicleCategoryForm {
  @SerializedName("name")
  private String name = null;

  @SerializedName("consumption")
  private BigDecimal consumption = null;

  @SerializedName("owner")
  private Integer owner = null;

  public UpdateVehicleCategoryVehicleCategoryForm name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "Test Category renamed", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public UpdateVehicleCategoryVehicleCategoryForm consumption(BigDecimal consumption) {
    this.consumption = consumption;
    return this;
  }

   /**
   * Get consumption
   * @return consumption
  **/
  @Schema(example = "1.2", description = "")
  public BigDecimal getConsumption() {
    return consumption;
  }

  public void setConsumption(BigDecimal consumption) {
    this.consumption = consumption;
  }

  public UpdateVehicleCategoryVehicleCategoryForm owner(Integer owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @Schema(example = "12", description = "")
  public Integer getOwner() {
    return owner;
  }

  public void setOwner(Integer owner) {
    this.owner = owner;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateVehicleCategoryVehicleCategoryForm updateVehicleCategoryVehicleCategoryForm = (UpdateVehicleCategoryVehicleCategoryForm) o;
    return Objects.equals(this.name, updateVehicleCategoryVehicleCategoryForm.name) &&
        Objects.equals(this.consumption, updateVehicleCategoryVehicleCategoryForm.consumption) &&
        Objects.equals(this.owner, updateVehicleCategoryVehicleCategoryForm.owner);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, consumption, owner);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateVehicleCategoryVehicleCategoryForm {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    consumption: ").append(toIndentedString(consumption)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
