/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.UserProfileLang;
import io.swagger.client.model.UserProfileListGeoLocalizationSettings;
import io.swagger.client.model.UserProfileListGroups;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * UserProfileListList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T07:00:05.887Z[GMT]")
public class UserProfileListList {
  @SerializedName("email")
  private String email = null;

  @SerializedName("groups")
  private List<UserProfileListGroups> groups = null;

  @SerializedName("locked")
  private Boolean locked = null;

  @SerializedName("firstname")
  private String firstname = null;

  @SerializedName("lastname")
  private String lastname = null;

  @SerializedName("phone")
  private String phone = null;

  @SerializedName("parent_id")
  private Integer parentId = null;

  @SerializedName("company")
  private String company = null;

  @SerializedName("id")
  private Integer id = null;

  @SerializedName("lang")
  private UserProfileLang lang = null;

  @SerializedName("geo_localization_settings")
  private UserProfileListGeoLocalizationSettings geoLocalizationSettings = null;

  public UserProfileListList email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @Schema(example = "example@example.com", description = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public UserProfileListList groups(List<UserProfileListGroups> groups) {
    this.groups = groups;
    return this;
  }

  public UserProfileListList addGroupsItem(UserProfileListGroups groupsItem) {
    if (this.groups == null) {
      this.groups = new ArrayList<UserProfileListGroups>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @Schema(description = "")
  public List<UserProfileListGroups> getGroups() {
    return groups;
  }

  public void setGroups(List<UserProfileListGroups> groups) {
    this.groups = groups;
  }

  public UserProfileListList locked(Boolean locked) {
    this.locked = locked;
    return this;
  }

   /**
   * Get locked
   * @return locked
  **/
  @Schema(description = "")
  public Boolean isLocked() {
    return locked;
  }

  public void setLocked(Boolean locked) {
    this.locked = locked;
  }

  public UserProfileListList firstname(String firstname) {
    this.firstname = firstname;
    return this;
  }

   /**
   * Get firstname
   * @return firstname
  **/
  @Schema(example = "Alexander", description = "")
  public String getFirstname() {
    return firstname;
  }

  public void setFirstname(String firstname) {
    this.firstname = firstname;
  }

  public UserProfileListList lastname(String lastname) {
    this.lastname = lastname;
    return this;
  }

   /**
   * Get lastname
   * @return lastname
  **/
  @Schema(example = "Alexandrov", description = "")
  public String getLastname() {
    return lastname;
  }

  public void setLastname(String lastname) {
    this.lastname = lastname;
  }

  public UserProfileListList phone(String phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  @Schema(example = "380994567378", description = "")
  public String getPhone() {
    return phone;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public UserProfileListList parentId(Integer parentId) {
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @Schema(example = "6", description = "")
  public Integer getParentId() {
    return parentId;
  }

  public void setParentId(Integer parentId) {
    this.parentId = parentId;
  }

  public UserProfileListList company(String company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @Schema(example = "Fake Company", description = "")
  public String getCompany() {
    return company;
  }

  public void setCompany(String company) {
    this.company = company;
  }

  public UserProfileListList id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "15", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public UserProfileListList lang(UserProfileLang lang) {
    this.lang = lang;
    return this;
  }

   /**
   * Get lang
   * @return lang
  **/
  @Schema(description = "")
  public UserProfileLang getLang() {
    return lang;
  }

  public void setLang(UserProfileLang lang) {
    this.lang = lang;
  }

  public UserProfileListList geoLocalizationSettings(UserProfileListGeoLocalizationSettings geoLocalizationSettings) {
    this.geoLocalizationSettings = geoLocalizationSettings;
    return this;
  }

   /**
   * Get geoLocalizationSettings
   * @return geoLocalizationSettings
  **/
  @Schema(description = "")
  public UserProfileListGeoLocalizationSettings getGeoLocalizationSettings() {
    return geoLocalizationSettings;
  }

  public void setGeoLocalizationSettings(UserProfileListGeoLocalizationSettings geoLocalizationSettings) {
    this.geoLocalizationSettings = geoLocalizationSettings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserProfileListList userProfileListList = (UserProfileListList) o;
    return Objects.equals(this.email, userProfileListList.email) &&
        Objects.equals(this.groups, userProfileListList.groups) &&
        Objects.equals(this.locked, userProfileListList.locked) &&
        Objects.equals(this.firstname, userProfileListList.firstname) &&
        Objects.equals(this.lastname, userProfileListList.lastname) &&
        Objects.equals(this.phone, userProfileListList.phone) &&
        Objects.equals(this.parentId, userProfileListList.parentId) &&
        Objects.equals(this.company, userProfileListList.company) &&
        Objects.equals(this.id, userProfileListList.id) &&
        Objects.equals(this.lang, userProfileListList.lang) &&
        Objects.equals(this.geoLocalizationSettings, userProfileListList.geoLocalizationSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, groups, locked, firstname, lastname, phone, parentId, company, id, lang, geoLocalizationSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserProfileListList {\n");
    
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    locked: ").append(toIndentedString(locked)).append("\n");
    sb.append("    firstname: ").append(toIndentedString(firstname)).append("\n");
    sb.append("    lastname: ").append(toIndentedString(lastname)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lang: ").append(toIndentedString(lang)).append("\n");
    sb.append("    geoLocalizationSettings: ").append(toIndentedString(geoLocalizationSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
