/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.VehicleBrandListInner;
import io.swagger.client.model.VehicleModelListList;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * VehicleVersionListList
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2020-02-20T07:00:05.887Z[GMT]")
public class VehicleVersionListList {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("brand")
  private VehicleBrandListInner brand = null;

  @SerializedName("model")
  private VehicleModelListList model = null;

  @SerializedName("started_at")
  private Integer startedAt = null;

  @SerializedName("ended_at")
  private String endedAt = null;

  @SerializedName("tonnage")
  private Integer tonnage = null;

  @SerializedName("power")
  private Integer power = null;

  @SerializedName("power_cv")
  private Integer powerCv = null;

  @SerializedName("axes")
  private String axes = null;

  public VehicleVersionListList id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(example = "1", description = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public VehicleVersionListList name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(example = "42.38", description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VehicleVersionListList brand(VehicleBrandListInner brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Get brand
   * @return brand
  **/
  @Schema(description = "")
  public VehicleBrandListInner getBrand() {
    return brand;
  }

  public void setBrand(VehicleBrandListInner brand) {
    this.brand = brand;
  }

  public VehicleVersionListList model(VehicleModelListList model) {
    this.model = model;
    return this;
  }

   /**
   * Get model
   * @return model
  **/
  @Schema(description = "")
  public VehicleModelListList getModel() {
    return model;
  }

  public void setModel(VehicleModelListList model) {
    this.model = model;
  }

  public VehicleVersionListList startedAt(Integer startedAt) {
    this.startedAt = startedAt;
    return this;
  }

   /**
   * Get startedAt
   * @return startedAt
  **/
  @Schema(example = "1322697600", description = "")
  public Integer getStartedAt() {
    return startedAt;
  }

  public void setStartedAt(Integer startedAt) {
    this.startedAt = startedAt;
  }

  public VehicleVersionListList endedAt(String endedAt) {
    this.endedAt = endedAt;
    return this;
  }

   /**
   * Get endedAt
   * @return endedAt
  **/
  @Schema(description = "")
  public String getEndedAt() {
    return endedAt;
  }

  public void setEndedAt(String endedAt) {
    this.endedAt = endedAt;
  }

  public VehicleVersionListList tonnage(Integer tonnage) {
    this.tonnage = tonnage;
    return this;
  }

   /**
   * Get tonnage
   * @return tonnage
  **/
  @Schema(example = "21000", description = "")
  public Integer getTonnage() {
    return tonnage;
  }

  public void setTonnage(Integer tonnage) {
    this.tonnage = tonnage;
  }

  public VehicleVersionListList power(Integer power) {
    this.power = power;
    return this;
  }

   /**
   * Get power
   * @return power
  **/
  @Schema(example = "280", description = "")
  public Integer getPower() {
    return power;
  }

  public void setPower(Integer power) {
    this.power = power;
  }

  public VehicleVersionListList powerCv(Integer powerCv) {
    this.powerCv = powerCv;
    return this;
  }

   /**
   * Get powerCv
   * @return powerCv
  **/
  @Schema(example = "381", description = "")
  public Integer getPowerCv() {
    return powerCv;
  }

  public void setPowerCv(Integer powerCv) {
    this.powerCv = powerCv;
  }

  public VehicleVersionListList axes(String axes) {
    this.axes = axes;
    return this;
  }

   /**
   * Get axes
   * @return axes
  **/
  @Schema(example = "4x2", description = "")
  public String getAxes() {
    return axes;
  }

  public void setAxes(String axes) {
    this.axes = axes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleVersionListList vehicleVersionListList = (VehicleVersionListList) o;
    return Objects.equals(this.id, vehicleVersionListList.id) &&
        Objects.equals(this.name, vehicleVersionListList.name) &&
        Objects.equals(this.brand, vehicleVersionListList.brand) &&
        Objects.equals(this.model, vehicleVersionListList.model) &&
        Objects.equals(this.startedAt, vehicleVersionListList.startedAt) &&
        Objects.equals(this.endedAt, vehicleVersionListList.endedAt) &&
        Objects.equals(this.tonnage, vehicleVersionListList.tonnage) &&
        Objects.equals(this.power, vehicleVersionListList.power) &&
        Objects.equals(this.powerCv, vehicleVersionListList.powerCv) &&
        Objects.equals(this.axes, vehicleVersionListList.axes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, brand, model, startedAt, endedAt, tonnage, power, powerCv, axes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleVersionListList {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    model: ").append(toIndentedString(model)).append("\n");
    sb.append("    startedAt: ").append(toIndentedString(startedAt)).append("\n");
    sb.append("    endedAt: ").append(toIndentedString(endedAt)).append("\n");
    sb.append("    tonnage: ").append(toIndentedString(tonnage)).append("\n");
    sb.append("    power: ").append(toIndentedString(power)).append("\n");
    sb.append("    powerCv: ").append(toIndentedString(powerCv)).append("\n");
    sb.append("    axes: ").append(toIndentedString(axes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
