/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AuthorizedUser;
import io.swagger.client.model.UserCredentials;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserAuthorizationApi
 */
@Ignore
public class UserAuthorizationApiTest {

    private final UserAuthorizationApi api = new UserAuthorizationApi();

    /**
     * 
     *
     * User authorization
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authorizeTest() throws ApiException {
        UserCredentials body = null;
        AuthorizedUser response = api.authorize(body);

        // TODO: test validations
    }
}
