/*
 * Gkeep API
 * Gkeep API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CountryList;
import io.swagger.client.model.TankTypeList;
import io.swagger.client.model.UserGroupList;
import io.swagger.client.model.VehicleBrandList;
import io.swagger.client.model.VehicleFuelTypeList;
import io.swagger.client.model.VehicleModelList;
import io.swagger.client.model.VehicleNationalTypeList;
import io.swagger.client.model.VehiclePropertyList;
import io.swagger.client.model.VehicleTypeList;
import io.swagger.client.model.VehicleVersionList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for V1Api
 */
@Ignore
public class V1ApiTest {

    private final V1Api api = new V1Api();

    /**
     * 
     *
     * Get countries
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCountriesListTest() throws ApiException {
        CountryList response = api.getCountriesList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get tank types
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTankTypeListTest() throws ApiException {
        TankTypeList response = api.getTankTypeList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get user allowed groups
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserGroupListTest() throws ApiException {
        UserGroupList response = api.getUserGroupList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle brands
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehicleBrandListTest() throws ApiException {
        VehicleBrandList response = api.getVehicleBrandList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle fuel-types
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehicleFuelTypesListTest() throws ApiException {
        VehicleFuelTypeList response = api.getVehicleFuelTypesList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle models
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehicleModelListTest() throws ApiException {
        String page = null;
        String perPage = null;
        VehicleModelList response = api.getVehicleModelList(page, perPage);

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle national-types
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehicleNationalTypeListTest() throws ApiException {
        VehicleNationalTypeList response = api.getVehicleNationalTypeList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle properties
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehiclePropertiesListTest() throws ApiException {
        VehiclePropertyList response = api.getVehiclePropertiesList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle types
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehicleTypeListTest() throws ApiException {
        VehicleTypeList response = api.getVehicleTypeList();

        // TODO: test validations
    }
    /**
     * 
     *
     * Get vehicle versions
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getVehicleVersionListTest() throws ApiException {
        String page = null;
        String perPage = null;
        VehicleVersionList response = api.getVehicleVersionList(page, perPage);

        // TODO: test validations
    }
}
